replicaCount: 1

image:
  repository: quay.io/ditto/sp-log-parser
  tag: sha-placeholder
  pullPolicy: Always

imagePullSecrets:
  - name: quay.io-cluster

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

probes:
  liveness:
    enabled: true
    httpGet:
      path: /health
    initialDelaySeconds: 10
  readiness:
    enabled: true
    httpGet:
      path: /health
    initialDelaySeconds: 5

configMap:
  enabled: false
  mountPath: ""

serviceAccount:
  create: false
  annotations: {}

env: []
podAnnotations: {}
harnessVersion: "0.0.1"
imageTag: ""

teleport:
  enabled: true
