replicaCount: 1

image:
  repository: quay.io/ditto/internal-tooling
  tag: small-peer-log-parser-latest
  pullPolicy: Always

imagePullSecrets:
  - name: quay.io-cluster

service:
  type: LoadBalancer
  port: 5000

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

probes:
  liveness:
    enabled: false
    httpGet:
      path: /
    initialDelaySeconds: 10
  readiness:
    enabled: false
    httpGet:
      path: /
    initialDelaySeconds: 5

configMap:
  enabled: false
  mountPath: ""

env: []
podAnnotations: {}
harnessVersion: "0.0.1"
imageTag: ""
