apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-api-staging-appset
  namespace: argo
spec:
  generators:
    - list:
        elements:
          - cluster: staging
            namespace: hello-api-staging
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: hello-api-{{.cluster}}
      labels:
        harness.io/envRef: helloapistaging
        harness.io/serviceRef: helloapiservice
    spec:
      project: mgmt-dev-usw2-ops-int-clusters
      source:
        repoURL: https://github.com/humzam-ditto/cloud-apps
        targetRevision: main
        path: apps/hello-api
        helm:
          valueFiles:
            - values.yaml
            - values-staging.yaml
            - harness-release.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  syncPolicy:
    applicationsSync: create-update
