{{- if .Values.teleport.enabled }}
apiVersion: resources.teleport.dev/v1
kind: TeleportAppV3
metadata:
  name: {{ include "common.fullname" . }}
  namespace: teleport-system
  labels:
    {{- include "common.labels" . | nindent 4 }}
    teleport.ditto.live/expose: "true"
spec:
  uri: "http://{{ include "common.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}"
{{- end }}
