replicaCount: 1

image:
  repository: nginx
  tag: "alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 32Mi

probes:
  liveness:
    enabled: false
    httpGet:
      path: /
    initialDelaySeconds: 10
  readiness:
    enabled: false
    httpGet:
      path: /
    initialDelaySeconds: 5

configMap:
  enabled: true
  mountPath: /usr/share/nginx/html

message: "Hello from the web frontend!"

env: []
podAnnotations: {}
harnessVersion: "0.0.1"
